"""Recreate migrations

Revision ID: 128a7ae7fc9f
Revises: 
Create Date: 2024-09-10 00:05:20.661060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128a7ae7fc9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(),
                            nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('company', sa.String(),
                            nullable=False, server_default='Unknown'))

        batch_op.add_column(sa.Column('position', sa.String(),
                            nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('interview_type', sa.String(),
                            nullable=False, server_default='Unknown'))

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint(
            'results_question_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('results_question_id_fkey', 'questions', [
                                    'question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('interview_type')
        batch_op.drop_column('position')
        batch_op.drop_column('company')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
