"""Add starter behavioral interview questions

Revision ID: 254e3cdd8f10
Revises: 6bfe394dbb4e
Create Date: 2024-07-27 23:32:44.100914

"""
from alembic import op
import sqlalchemy as sa



revision = '254e3cdd8f10'
down_revision = '6bfe394dbb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    starter_questions = [
        "Tell me about a time when you had to work closely with someone whose personality was very different from yours.",
        "Give me an example of a time you faced a conflict while working on a team. How did you handle that?",
        "Describe a time when you had to manage multiple responsibilities. How did you handle it?",
        "Tell me about a time you had to learn something new within a short deadline. How did you approach it?",
        "Describe a time when you had to deal with a difficult customer or client. What did you do?"
    ]

    for question in starter_questions:
        op.execute(
            f"INSERT INTO questions (question) VALUES ('{question}')"
        )
 


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    starter_questions = [
        "Tell me about a time when you had to work closely with someone whose personality was very different from yours.",
        "Give me an example of a time you faced a conflict while working on a team. How did you handle that?",
        "Describe a time when you had to manage multiple responsibilities. How did you handle it?",
        "Tell me about a time you had to learn something new within a short deadline. How did you approach it?",
        "Describe a time when you had to deal with a difficult customer or client. What did you do?"
    ]

    for question in starter_questions:
        op.execute(
            f"DELETE FROM questions WHERE question = '{question}'"
        )
    # ### end Alembic commands ###
