"""Add audio_url column

Revision ID: 8c1bdef23e4e
Revises: c1bffc9ab80f
Create Date: 2024-07-28 20:02:04.758299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1bdef23e4e'
down_revision = 'c1bffc9ab80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'audio_url')
    # ### end Alembic commands ###
